import { LineKinds, IStoryLine } from "@/interfaces/story_line";

export const lines: IStoryLine[] = [
  // MARK: - Main Story
  {
    id: 0,
    kind: LineKinds.title,
    text: '☆',
    talker: null,
    nextLineId: 1,
  },
  {
    id: 1,
    kind: LineKinds.title,
    text: 'O universo não me acolheu.',
    isHe: true,
    talker: null,
    nextLineId: 2,
    initialDelay: 2000,
  },
  {
    id: 2,
    kind: LineKinds.title,
    text: 'Mas não era dele que eu precisava.',
    isHe: true,
    talker: null,
    nextLineId: 3,
  },
  {
    id: 3,
    kind: LineKinds.title,
    text: 'Eu nunca precisei.',
    isHe: true,
    talker: null,
    nextLineId: 4,
  },
  {
    id: 4,
    kind: LineKinds.line,
    text: 'Na verdade, não é como se essa fosse a obrigação dele.',
    nextLineId: 5,
    talker: '?',
  },
  {
    id: 5,
    kind: LineKinds.line,
    text: 'Mas mesmo assim. ####Eu te entendo.########## Também gostaria de, ao menos uma vez, fazer parte de alguma coisa.',
    nextLineId: 6,
    talker: '?',
  },
  {
    id: 6,
    kind: LineKinds.line,
    text: 'Não necessariamente algo tão######### grande. Como o universo.',
    nextLineId: 7,
    talker: '?',
  },
  {
    id: 7,
    kind: LineKinds.line,
    text: 'Só algo que######### me fizesse me sentir em casa.',
    nextLineId: 8,
    talker: '?',
  },
  {
    id: 8,
    kind: LineKinds.title,
    text: 'C#########A#########S#########A',
    isHe: true,
    nextLineId: 9,
  },
  {
    id: 9,
    kind: LineKinds.title,
    text: 'Casa se foi###########@há muito tempo.',
    isHe: true,
    talker: null,
    nextLineId: 10,
  },
  {
    id: 10,
    kind: LineKinds.line,
    text: 'Tem razão########, estou completamente sozinho.###### . ######.',
    nextLineId: 11,
    talker: '?',
  },
  {
    id: 11,
    kind: LineKinds.line,
    text: 'Eu poderia só#####.#####.#####.###### deixar tudo isso para trás.',
    nextLineId: 12,
    talker: '?',
  },
  {
    id: 12,
    kind: LineKinds.line,
    text: 'Não há nada para mim aqui.',
    nextLineId: 13,
    talker: '?',
  },
  {
    id: 13,
    kind: LineKinds.line,
    text: 'A única coisa que posso fazer é parar.###### Admirar esse céu.### E fingir que, no meio de todas aquelas estrelas##########, existe um lugar para mim.',
    nextLineId: 14,
    talker: '?',
  },
  {
    id: 14,
    kind: LineKinds.title,
    text: 'Não########.',
    isHe: true,
    nextLineId: 15,
  },
  {
    id: 15,
    kind: LineKinds.line,
    text: 'Tem razão.',
    nextLineId: 16,
    talker: '?',
    initialDelay: 2000,
  },
  {
    id: 16,
    kind: LineKinds.line,
    text: 'Isso é burrice',
    nextLineId: 17,
    talker: '?',
  },
  {
    id: 17,
    kind: LineKinds.line,
    text: 'Ou ser muito ingênuo.',
    nextLineId: 18,
    talker: '?',
  },
  {
    id: 18,
    kind: LineKinds.title,
    text: 'Finalmente, você est%',
    isHe: true,
    nextLineId: 19,
  },
  {
    id: 19,
    kind: LineKinds.line,
    text: 'Espera#####, o que é aquilo?',
    nextLineId: 20,
    talker: '?',
  },
  {
    id: 20,
    kind: LineKinds.line,
    text: '\u00C9 tão####### lindo.',
    nextLineId: 21,
    talker: '?',
  },
  {
    id: 21,
    kind: LineKinds.title,
    text: 'Não me igno%',
    isHe: true,
    nextLineId: 22,
  },
  {
    id: 22,
    kind: LineKinds.line,
    text: 'Caramba, ####que vista incrível',
    nextLineId: 23,
    talker: '?',
  },
  {
    id: 23,
    kind: LineKinds.line,
    text: 'Nunca havia visto algo tão deslumbrante.',
    nextLineId: 24,
    talker: '?',
    firstOption: 'Chamar',
    secondOption: 'Olhar de mais perto',
    firstOptionLineId: 25,
    secondOptionLineId: 27,
  },
  {
    id: 25,
    kind: LineKinds.line,
    text: 'Ol-%',
    nextLineId: 26,
    talker: '?',
    initialDelay: 2000,
  },
  {
    id: 26,
    kind: LineKinds.line,
    text: 'Espera, o que eu tô fazendo? #######@Não deveria acordá-la.######### Além disso, não sei seu nome para que pudesse chamá-la.',
    nextLineId: 27,
    talker: '?',
  },
  {
    id: 27,
    kind: LineKinds.line,
    text: 'Talvez eu possa apenas admirá-la de mais perto.',
    nextLineId: 28,
    talker: '?',
  },
  {
    id: 28,
    kind: LineKinds.line,
    text: 'Ela deve ficar mais próxima do outro lado da montanha. @######Certo.',
    nextLineId: 29,
    talker: '?',
  },
  {
    id: 29,
    kind: LineKinds.narrative,
    text: 'Ainda não sei o que me motivou a fazer isso. ##########Mas senti que valia a pena.',
    nextLineId: 30,
  },
  {
    id: 30,
    kind: LineKinds.narrative,
    text: '"Por que aquele corpo celeste tanto me encantou? Será que todo mundo tinha visto o que eu acabara de ver?"',
    nextLineId: 31,
    initialDelay: 3000,
  },
  {
    id: 31,
    kind: LineKinds.narrative,
    text: 'Perguntas intermináveis ecoavam em meu interior, aquele ser não era comum. #######E isso me fazia ainda mais aficionado por ela.',
    nextLineId: 32,
  },
  {
    id: 32,
    kind: LineKinds.narrative,
    text: 'Durante todo o trajeto, Ele não disse mais nada.######## A caminhada não durou tanto, mas eu nunca tinha visto Ele tão########### quieto.',
    nextLineId: 33,
  },
  {
    id: 33,
    kind: LineKinds.narrative,
    text: 'Enfim, . . .',
    nextLineId: 34,
  },
  {
    id: 34,
    kind: LineKinds.line,
    text: '...chegamos',
    nextLineId: 35,
    talker: '?',
  },
  {
    id: 35,
    kind: LineKinds.line,
    text: 'Esse lado da montanha fica mais próximo do topo. ####Parece que o céu também mudou.',
    nextLineId: 36,
    talker: '?',
  },
  {
    id: 36,
    kind: LineKinds.line,
    text: 'Será que foi ela?',
    nextLineId: 37,
    talker: '?',
  },
  {
    id: 37,
    kind: LineKinds.line,
    text: 'Correto.',
    nextLineId: 38,
    talker: '????',
  },
  {
    id: 38,
    kind: LineKinds.line,
    text: 'Espera, o que? Quem disse isso?',
    nextLineId: 39,
    talker: '?',
  },
  {
    id: 39,
    kind: LineKinds.line,
    text: 'Eu, aqui em cima.### Você me acordou.',
    nextLineId: 40,
    talker: 'Estrela',
  },
  {
    id: 40,
    kind: LineKinds.line,
    text: '###.###.###.',
    nextLineId: 41,
    talker: '?',
  },
  {
    id: 41,
    kind: LineKinds.line,
    text: '####.####.####.############# !!!!!',
    nextLineId: 42,
    talker: 'Estrela',
  },
  {
    id: 42,
    kind: LineKinds.narrative,
    text: 'Ela realmente parecia estar tão assustada quanto eu.',
    nextLineId: 43,
  },
  {
    id: 43,
    kind: LineKinds.narrative,
    text: 'Talvez ela queira ajuda, assim como eu?',
    nextLineId: 44,
  },
  {
    id: 44,
    kind: LineKinds.title,
    text: '#V#o#c#ê  #n#ã#o #p#r#e#c#i#s#a #d#e #a#j#u#d#a.',
    isHe: true,
    nextLineId: 45,
  },
  {
    id: 45,
    kind: LineKinds.line,
    text: 'Por favor, agora não.',
    nextLineId: 46,
    talker: '?',
  },
  {
    id: 46,
    kind: LineKinds.line,
    text: 'Ah.## Tudo bem#######! ##########.####.####.',
    nextLineId: 47,
    talker: 'Estrela',
  },
  {
    id: 47,
    kind: LineKinds.line,
    text: 'Espera, não era com você.',
    nextLineId: 48,
    talker: '?',
  },
  {
    id: 48,
    kind: LineKinds.line,
    text: 'Ah##.##.##.',
    nextLineId: 49,
    talker: 'Estrela',
  },
  {
    id: 49,
    kind: LineKinds.narrative,
    text: 'Ela parecia incomodada com algo. #####Mas não acho que queria falar sobre.',
    nextLineId: 50,
  },
  {
    id: 50,
    kind: LineKinds.line,
    text: 'Então...',
    talker: '?',
    nextLineId: -1,
    firstOption: 'Como você se chama?',
    secondOption: 'Qual é o problema?',
    firstOptionLineId: 108,
    secondOptionLineId: 51,
  },
  {
    id: 51,
    kind: LineKinds.line,
    text: 'Tem algo de errado?',
    nextLineId: 52,
    talker: '?',
  },
  {
    id: 52,
    kind: LineKinds.line,
    text: '####.####.#####.%',
    nextLineId: 53,
    talker: 'Estrela',
  },
  {
    id: 53,
    kind: LineKinds.line,
    text: '##########Ele me assusta.',
    nextLineId: 54,
    talker: 'Estrela',
  },
  {
    id: 54,
    kind: LineKinds.line,
    text: 'Ele qu-@Ah, Ele? #######Espera, você consegue ver?',
    nextLineId: 55,
    talker: '?',
  },
  {
    id: 55,
    kind: LineKinds.line,
    text: '...',
    nextLineId: 56,
    talker: 'Estrela',
  },
  {
    id: 56,
    kind: LineKinds.line,
    text: 'Entendo.#### Ele costumava me assustar também. Agora...####### já é parte de mim.',
    nextLineId: 57,
    talker: '?',
  },
  {
    id: 57,
    kind: LineKinds.line,
    text: 'Mas olha só, foi só você chegar que ele se foi, então #######obrigado. De verdade.',
    nextLineId: 58,
    talker: '?',
  },
  {
    id: 58,
    kind: LineKinds.line,
    text: 'Você precisa se livrar dele.',
    nextLineId: 59,
    talker: 'Estrela',
  },
  {
    id: 59,
    kind: LineKinds.line,
    text: 'O que? Mas ele já%',
    nextLineId: 60,
    talker: '?',
  },
  {
    id: 60,
    kind: LineKinds.line,
    text: 'Não.',
    nextLineId: 61,
    talker: 'Estrela',
  },
  {
    id: 61,
    kind: LineKinds.none,
    text: '',
    nextLineId: 62,
    timeout: 3000,
  },
  {
    id: 62,
    kind: LineKinds.title,
    text: 'Ele ainda está aqui.',
    nextLineId: 63,
  },
  {
    id: 63,
    kind: LineKinds.line,
    text: 'Não',
    nextLineId: 64,
    talker: '?',
  },
  {
    id: 64,
    kind: LineKinds.line,
    text: 'Me deixa em paz, por favor.',
    nextLineId: 65,
    talker: '?',
    tilting: true,
  },
  {
    id: 65,
    kind: LineKinds.line,
    text: 'Ei##%',
    nextLineId: 66,
    talker: 'Estrela',
  },
  {
    id: 66,
    kind: LineKinds.title,
    text: 'Está na hora de terminarmos o que começamos.',
    isHe: true,
    nextLineId: 67,
  },
  {
    id: 67,
    kind: LineKinds.line,
    text: 'Por favor, acaba logo com isso.',
    nextLineId: 68,
    talker: '?',
    tilting: true,
  },
  {
    id: 68,
    kind: LineKinds.line,
    text: 'Ei.##### Tá tudo bem. Ele não pode te machucar.',
    nextLineId: 69,
    talker: 'Estrela',
  },
  {
    id: 69,
    kind: LineKinds.line,
    text: 'Eu tô com tanto medo.',
    nextLineId: 70,
    talker: '?',
    tilting: true,
  },
  {
    id: 70,
    kind: LineKinds.line,
    text: 'Vai ficar tudo bem. Você não está sozinho.',
    nextLineId: 71,
    talker: 'Estrela',
  },
  {
    id: 71,
    kind: LineKinds.title,
    text: 'Você está sozinho.',
    isHe: true,
    nextLineId: 72,
  },
  {
    id: 72,
    kind: LineKinds.line,
    text: 'Eu##### tô sozinho. ######Eu mereço######## ficar sozinho.',
    nextLineId: 73,
    talker: '?',
  },
  {
    id: 73,
    kind: LineKinds.line,
    text: 'Eu estou aqui.##### Aqui com você.',
    nextLineId: 74,
    talker: 'Estrela',
  },
  {
    id: 74,
    kind: LineKinds.line,
    text: 'Não há mais nada para mim aqui.',
    nextLineId: 75,
    talker: '?',
  },
  {
    id: 75,
    kind: LineKinds.none,
    text: '',
    nextLineId: 76,
    talker: '?',
    timeout: 3000,
  },
  {
    id: 76,
    kind: LineKinds.line,
    text: 'Você tem a mim.',
    nextLineId: 77,
    talker: 'Estrela',
  },
  {
    id: 77,
    kind: LineKinds.line,
    text: 'Como pode se oferecer tanto para me ajudar sem me conhecer? ###E se eu não merecer sua ajuda?########## E se eu merecer me sentir assim?',
    nextLineId: 78,
    talker: '?',
  },
  {
    id: 78,
    kind: LineKinds.line,
    text: 'Talvez você mereça isso.### Talvez você não queira minha ajuda.##### Mas você tem uma chance de se fazer valer a pena.',
    nextLineId: 79,
    talker: 'Estrela',
  },
  {
    id: 79,
    kind: LineKinds.line,
    text: 'E então, é o que você quer?',
    nextLineId: -1,
    talker: 'Estrela',
    firstOptionLineId: 80,
    secondOptionLineId: 175,
    firstOption: 'Sim, eu quero.',
    secondOption: 'Não sei se consigo',
  },
  {
    id: 80,
    kind: LineKinds.line,
    text: 'Eu#####.###.###.###########%',
    nextLineId: 81,
    tilting: true,
    talker: '?',
  },
  {
    id: 81,
    kind: LineKinds.line,
    text: 'Sim#######, é o que quero.######## Gostaria de não ser tão fraco.',
    nextLineId: 82,
    tilting: true,
    talker: '?',
  },
  {
    id: 82,
    kind: LineKinds.line,
    text: 'Você não é fraco, só precisa de uma direção.############%',
    nextLineId: 83,
    talker: 'Estrela',
  },
  {
    id: 83,
    kind: LineKinds.none,
    text: '',
    nextLineId: 84,
    timeout: 5000,
  },
  {
    id: 84,
    kind: LineKinds.title,
    text: 'Por isso, eu estou aqui. ######Com você.',
    nextLineId: 85,
  },
  {
    id: 85,
    kind: LineKinds.none,
    text: '',
    nextLineId: 86,
    timeout: 7000,
  },
  {
    id: 86,
    kind: LineKinds.line,
    text: 'Os anos se passaram e,##### enfim posso afirmar:',
    nextLineId: 87,
    talker: '?',
  },
  {
    id: 87,
    kind: LineKinds.title,
    text: 'O universo########## me acolheu.',
    nextLineId: 88,
  },
  {
    id: 88,
    kind: LineKinds.title,
    text: 'Não sei o porquê###### e ainda não entendo se o merecia.',
    nextLineId: 89,
  },
  {
    id: 89,
    kind: LineKinds.title,
    text: 'Mas me foi concedida a oportunidade @de fazer tudo o que vivi até agora###### valer a pena.',
    nextLineId: 90,
  },
  {
    id: 90,
    kind: LineKinds.title,
    text: 'E, por isso, eu agradeço.',
    nextLineId: 91,
  },
  {
    id: 91,
    kind: LineKinds.title,
    text: 'Agradeço a você.',
    nextLineId: 92,
  },
  {
    id: 92,
    kind: LineKinds.none,
    text: '',
    timeout: 3000,
    nextLineId: 93,
  },
  {
    id: 93,
    kind: LineKinds.title,
    text: 'Agradeço a você.##### Todos os dias.',
    nextLineId: 94,
  },
  {
    id: 94,
    kind: LineKinds.title,
    text: 'Espero um dia poder retribuir o que fez por mim.',
    nextLineId: 95,
  },
  {
    id: 95,
    kind: LineKinds.title,
    text: 'Porém######, enquanto esse dia não chega.##.##.',
    nextLineId: 96,
  },
  {
    id: 96,
    kind: LineKinds.title,
    text: 'Eu te amo.',
    nextLineId: 97,
  },
  {
    id: 97,
    kind: LineKinds.title,
    text: 'Te amo#########, como nunca amei alguém.',
    nextLineId: 98,
  },
  {
    id: 98,
    kind: LineKinds.title,
    text: 'Mais do que ontem######, menos do que amarei amanhã.',
    nextLineId: 99,
  },
  {
    id: 99,
    kind: LineKinds.title,
    text: 'E espero que o amanhã sempre chegue.',
    nextLineId: 100,
  },
  {
    id: 100,
    kind: LineKinds.title,
    text: 'Para que eu possa###, mais uma vez, viajar por seus olhos de nebulosa.',
    nextLineId: 101,
  },
  {
    id: 101,
    kind: LineKinds.title,
    text: 'Para que eu possa ver seu sorriso, o mais brilhante do céu noturno.',
    nextLineId: 102,
  },
  {
    id: 102,
    kind: LineKinds.title,
    text: 'Para que eu nunca precise dizer adeus.',
    nextLineId: 103,
  },
  {
    id: 102,
    kind: LineKinds.title,
    text: 'Adeus para a estrela que dominou o meu céu e governou minha galáxia.',
    nextLineId: 103,
  },
  {
    id: 103,
    kind: LineKinds.title,
    text: 'Pois a pior parte disso####### é te deixar.',
    nextLineId: 104,
  },
  {
    id: 104,
    kind: LineKinds.line,
    text: 'Então, fique comigo.',
    nextLineId: 105,
  },
  {
    id: 105,
    kind: LineKinds.none,
    text: '',
    timeout: 2000,
    nextLineId: 106
  },
  {
    id: 106,
    kind: LineKinds.title,
    text: 'Até que viremos supernovas.###########################################################################################################################################################################',
    nextLineId: 107,
  },

  // MARK: - Secondary Story
  {
    id: 108,
    kind: LineKinds.line,
    text: 'Você tem#### um nome?###### Nunca te vi antes, mesmo com tanto tempo para contemplar o céu.',
    nextLineId: 109,
    talker: '?',
  },
  {
    id: 109,
    kind: LineKinds.line,
    text: 'Um####.####.###.####### nome?',
    nextLineId: 110,
    talker: 'Estrela',
  },
  {
    id: 110,
    kind: LineKinds.line,
    text: 'Isso.#### Sabe, várias estrelas possuem nomes para que possamos identificá-las, como a estrela mais brilhante observável da Terra, sem contar o Sol: Sirius.',
    nextLineId: 111,
    talker: '?',
  },
  {
    id: 111,
    kind: LineKinds.narrative,
    text: 'A mais brilhante até agora.',
    nextLineId: 112,
  },
  {
    id: 112,
    kind: LineKinds.line,
    text: 'Ah###.###.###.##### acho que não tenho isso.######.########.',
    nextLineId: 113,
    talker: 'Estrela',
  },
  {
    id: 113,
    kind: LineKinds.line,
    text: 'Na verdade###, agora que você falou sobre o Sol, lembrei que##### eu não deveria estar aqui.',
    nextLineId: 114,
    talker: 'Estrela',
  },
  {
    id: 114,
    kind: LineKinds.line,
    text: 'O quê?#### Espera%',
    nextLineId: 115,
    talker: '?',
  },
  {
    id: 115,
    kind: LineKinds.title,
    text: 'F#####R#####A#####C#####O',
    isHe: true,
    nextLineId: 116,
  },
  {
    id: 116,
    kind: LineKinds.line,
    text: '##.##.##.',
    nextLineId: 117,
    talker: '?',
  },
  {
    id: 117,
    kind: LineKinds.line,
    text: 'Eu sei.',
    nextLineId: 118,
    talker: '?',
  },
  {
    id: 118,
    kind: LineKinds.none,
    text: '',
    nextLineId: 119,
    talker: '?',
  },
  {
    id: 119,
    kind: LineKinds.line,
    text: 'N##ã##o.',
    nextLineId: 120,
    talker: 'Estrela',
  },
  {
    id: 120,
    kind: LineKinds.line,
    text: 'Hm?',
    nextLineId: 121,
    talker: '?',
  },
  {
    id: 121,
    kind: LineKinds.line,
    text: 'Você####.#.###.###### não é isso.############ Não é fraco.',
    nextLineId: 122,
    talker: 'Estrela',
  },
  {
    id: 122,
    kind: LineKinds.line,
    text: 'Eu sou.##### Sou um fracasso.',
    nextLineId: 123,
    talker: 'Estrela',
  },
  {
    id: 123,
    kind: LineKinds.narrative,
    text: 'Novamente, ela deixa escapar um pouco de sua sensibilidade.',
    nextLineId: 124,
  },
  {
    id: 124,
    kind: LineKinds.narrative,
    text: 'Novamente, ela conseguiu superar qualquer expectativa minha em relação ao quanto ela é incrível. Como ela conseguiu ouvir ele? Deixei tão aparente assim?',
    nextLineId: 125,
  },
  {
    id: 125,
    kind: LineKinds.line,
    text: 'Por que diz isso?',
    nextLineId: 126,
    talker: '?',
  },
  {
    id: 126,
    kind: LineKinds.line,
    text: 'Você parece alguém muito interessante e inteligente.',
    nextLineId: 127,
    talker: '?',
  },
  {
    id: 127,
    kind: LineKinds.narrative,
    text: 'E muito linda.####### Mas não queria que ela me visse como alguém superficial.',
    nextLineId: 128,
  },
  {
    id: 128,
    kind: LineKinds.line,
    text: 'Ainda não se perguntou como vim parar aqui?',
    nextLineId: 129,
    talker: 'Estrela',
  },
  {
    id: 129,
    kind: LineKinds.line,
    text: 'Eu sou diferente delas.',
    nextLineId: 130,
    talker: 'Estrela',
  },
  {
    id: 130,
    kind: LineKinds.line,
    text: 'Diferente dos seres que compõem esse céu.####### Os quais você contempla todas as noites.######## Mais estranha. #######Bem########### mais estranha.',
    nextLineId: 131,
    talker: 'Estrela',
  },
  {
    id: 131,
    kind: LineKinds.line,
    text: 'Não pude superar me sentir menos brilhante e atrativa do que elas.######### Então, me afastei.',
    nextLineId: 132,
    talker: 'Estrela',
  },
  {
    id: 132,
    kind: LineKinds.line,
    text: 'Consequentemente, também nunca me foi dado um nome.',
    nextLineId: 133,
    talker: 'Estrela',
  },
  {
    id: 133,
    kind: LineKinds.line,
    text: 'Eu sinto muito.',
    nextLineId: 134,
    talker: '?',
  },
  {
    id: 134,
    kind: LineKinds.title,
    text: 'Isso não ajuda em nada',
    isHe: true,
    nextLineId: 135,
  },
  {
    id: 135,
    kind: LineKinds.line,
    text: 'Tem razão.',
    nextLineId: 136,
    talker: '?',
  },
  {
    id: 136,
    kind: LineKinds.line,
    text: 'E se#### eu te desse um nome?',
    nextLineId: 137,
    talker: '?',
  },
  {
    id: 137,
    kind: LineKinds.line,
    text: 'Sei que deve ser estranho mas#### acho que devo ser o primeiro a ver você.',
    nextLineId: 138,
    talker: '?',
  },
  {
    id: 138,
    kind: LineKinds.line,
    text: 'Não me parece má ideia.',
    nextLineId: 139,
    talker: 'Estrela',
  },
  {
    id: 139,
    kind: LineKinds.line,
    text: 'Eu confio em você.########### Não foi o primeiro a me ver, mas foi o único a me olhar.',
    nextLineId: 140,
    talker: 'Estrela',
  },
  {
    id: 140,
    kind: LineKinds.narrative,
    text: 'Não entendi a diferença.### Mas percebi que####, mesmo que discretamente, ela passou a confiar em mim.',
    nextLineId: 141,
  },
  {
    id: 141,
    kind: LineKinds.line,
    text: 'Então, seu nome será...',
    nextLineId: 142,
    talker: '?',
  },
  {
    id: 142,
    kind: LineKinds.input,
    text: '',
    nextLineId: -1,
    firstOptionLineId: 143,
    secondOptionLineId: 168,
  },

  /// MARK:- Her name
  {
    id: 143,
    kind: LineKinds.line,
    text: '#######.######.##########.%',
    nextLineId: 144,
    talker: 'Estrela',
  },
  {
    id: 144,
    kind: LineKinds.line,
    text: '....+######?',
    nextLineId: 145,
    talker: 'Estrela',
  },
  {
    id: 145,
    kind: LineKinds.line,
    text: 'Você.####.####.## não gos%',
    nextLineId: 146,
    talker: '?',
  },
  {
    id: 146,
    kind: LineKinds.line,
    text: 'Eu####.#####.#####.#### adorei!##!#!',
    nextLineId: 147,
    talker: 'star_name',
  },
  {
    id: 147,
    kind: LineKinds.line,
    text: 'Eu########### não acredito que finalmente tenho um nome#######, pode não parecer muito para você mas para mim é tudo.%',
    nextLineId: 148,
    talker: 'star_name',
  },
  {
    id: 148,
    kind: LineKinds.line,
    text: 'Finalmente me sinto alguém. ######Finalmente serei eu mesma.######### +. Você não sabe o quanto estou feliz.%',
    nextLineId: 149,
    talker: 'star_name',
  },
  {
    id: 149,
    kind: LineKinds.none,
    text: '',
    nextLineId: 150,
    timeout: 2000,
  },
  {
    id: 150,
    kind: LineKinds.title,
    text: 'Há algum tempo que eu não sentia coisa parecida.',
    nextLineId: 151,
  },
  {
    id: 151,
    kind: LineKinds.narrative,
    text: 'Depois daquilo, ficamos cada vez mais próximos.',
    nextLineId: 152,
  },
  {
    id: 152,
    kind: LineKinds.narrative,
    text: 'E estivemos juntos.######## Em todas as noites.',
    nextLineId: 153,
  },
  {
    id: 153,
    kind: LineKinds.narrative,
    text: 'Em pouco tempo, ela já fazia parte do meu dia todo, todos os dias.',
    nextLineId: 154,
  },
  {
    id: 154,
    kind: LineKinds.narrative,
    text: 'Os mesmos meus dias.####### Os quais eu, antes, preferia não vivenciar mais.',
    nextLineId: 155,
  },
  {
    id: 155,
    kind: LineKinds.narrative,
    text: 'Hoje########, esses dias são o motivo de eu abrir os olhos.',
    nextLineId: 156,
  },
  {
    id: 156,
    kind: LineKinds.narrative,
    text: 'E descobri###### que isso é viver:',
    nextLineId: 157,
  },
  {
    id: 157,
    kind: LineKinds.narrative,
    text: 'Suportar a vida.############### Até encontrar aquilo que torna a mesma suportável.##############@Aquilo que a torna digna de ser vivida.',
    nextLineId: 158,
  },
  {
    id: 158,
    kind: LineKinds.title,
    text: 'E é a você que eu agradeço por me fazer perceber isso.',
    nextLineId: 159,
  },
  {
    id: 159,
    kind: LineKinds.title,
    text: 'Que eu realmente##### nunca precisei que o universo me acolhesse.',
    nextLineId: 160,
  },
  {
    id: 160,
    kind: LineKinds.none,
    text: '',
    timeout: 7000,
    nextLineId: 161,
  },
  {
    id: 161,
    kind: LineKinds.title,
    text: 'Eu só precisava de você.',
    nextLineId: 162,
  },
  {
    id: 162,
    kind: LineKinds.title,
    text: 'Você sempre foi alguém.####### O tempo todo, teve seu lugar no céu.',
    nextLineId: 163,
  },
  {
    id: 163,
    kind: LineKinds.title,
    text: 'Você só precisava enxergar isso.############## Apenas nisso, o seu nome te ajudou.',
    nextLineId: 164,
  },
  {
    id: 164,
    kind: LineKinds.none,
    text: '',
    timeout: 3000,
    nextLineId: 165,
  },
  {
    id: 165,
    kind: LineKinds.title,
    text: '"+"###########.',
    nextLineId: 166,
  },
  {
    id: 166,
    kind: LineKinds.title,
    text: 'Realmente, é um belo nome###### para o meu universo.',
    nextLineId: 167,
  },
  {
    id: 167,
    kind: LineKinds.title,
    text: 'Obrigado.',
    nextLineId: 168,
  },
  {
    id: 168,
    kind: LineKinds.title,
    text: 'Por fazer parte do meu céu.',
    nextLineId: -1,
  },

  /// MARK:- Not her name
  {
    id: 168,
    kind: LineKinds.line,
    text: '#######.######.##########.%',
    nextLineId: 169,
    talker: 'Estrela',
  },
  {
    id: 169,
    kind: LineKinds.line,
    text: '....+######?',
    nextLineId: 170,
    talker: 'Estrela',
  },
  {
    id: 170,
    kind: LineKinds.line,
    text: 'Você.####.####.## não gos%',
    nextLineId: 171,
    talker: '?',
  },
  {
    id: 171,
    kind: LineKinds.line,
    text: 'Ei, relaxa! Eu gostei.###### Só##.##.##.## é engraçado.',
    nextLineId: 172,
    talker: 'star_name',
  },
  {
    id: 172,
    kind: LineKinds.line,
    text: 'Pensar que há pouco eu não tinha um nome e agora eu tenho um tão##.##.##.##### bom.',
    nextLineId: 173,
    talker: 'star_name',
  },
  {
    id: 173,
    kind: LineKinds.line,
    text: 'Sabe####################, até que gosto de você.#########%',
    nextLineId: 174,
    talker: 'star_name',
  },
  {
    id: 174,
    kind: LineKinds.none,
    text: '',
    nextLineId: 150,
    timeout: 5000,
  },

  // MARK:- Can't fight
  {
    id: 175,
    kind: LineKinds.line,
    text: 'Tudo bem.##.#####.',
    nextLineId: 176,
    talker: 'Estrela',
  },
  {
    id: 176,
    kind: LineKinds.line,
    text: 'Mas eu não posso lutar no seu lugar.',
    nextLineId: 177,
    talker: 'Estrela',
  },
  {
    id: 177,
    kind: LineKinds.line,
    text: 'Nos falamos novamente###.###.##. Quando você se livrar desse peso. *** **** ***** ********.',
    nextLineId: 178,
    talker: 'Estrela',
  },
  {
    id: 178,
    kind: LineKinds.narrative,
    text: 'Ela se foi, murmurando algo que não consegui ouvir.',
    nextLineId: 179,
  },
  {
    id: 179,
    kind: LineKinds.title,
    isHe: true,
    text: 'Você perdeu.######## Babaca.',
    nextLineId: -1,
    firstOption: 'Reiniciar',
    secondOption: 'Reiniciar',
    firstOptionLineId: 79,
    secondOptionLineId: 79,
  },
]