import { LineKinds, IStoryLine } from "@/interfaces/story_line";

export const lines: IStoryLine[] = [ 
  {
    id: 1,
    kind: LineKinds.title,
    text: 'O universo não me acolheu.',
    nextLineId: 2,
    talker: null,
  },
  {
    id: 2,
    kind: LineKinds.title,
    text: 'Mas não era dele que eu precisava.',
    nextLineId: 3,
    talker: null,
  },
  {
    id: 3,
    kind: LineKinds.title,
    text: 'Eu nunca precisei.',
    nextLineId: 4,
    talker: null,
  },
  {
    id: 4,
    kind: LineKinds.line,
    text: 'Na verdade, não é como se essa fosse a obrigação dele.',
    nextLineId: 5,
    talker: '?',
  },
  {
    id: 5,
    kind: LineKinds.line,
    text: 'Mas mesmo assim. ####Eu te entendo.########## Também gostaria de, ao menos uma vez, fazer parte de alguma coisa.',
    nextLineId: 6,
    talker: '?',
  },
  {
    id: 6,
    kind: LineKinds.line,
    text: 'Não necessariamente algo#### grande.',
    nextLineId: 7,
    talker: '?',
  },
  {
    id: 7,
    kind: LineKinds.line,
    text: 'Só algo que,######## sei lá, o qual eu pudesse chamar de##.###.###.## casa########?',
    nextLineId: 8,
    talker: '?',
  },
  {
    id: 8,
    kind: LineKinds.title,
    text: 'C#########A#########S#########A',
    nextLineId: 9,
  },
  {
    id: 9,
    kind: LineKinds.title,
    text: 'Casa se foi###########@há muito tempo.',
    nextLineId: 10,
    talker: null,
  },
  {
    id: 10,
    kind: LineKinds.line,
    text: 'Tem razão########, estou completamente sozinho.###### . ######.',
    nextLineId: 11,
    talker: '?',
  },
  {
    id: 11,
    kind: LineKinds.line,
    text: 'Eu poderia só#####.#####.#####.###### deixar tudo isso para trás.',
    nextLineId: 12,
    talker: '?',
  },
  {
    id: 12,
    kind: LineKinds.line,
    text: 'Não há nada para mim aqui.',
    nextLineId: 13,
    talker: '?',
  },
  {
    id: 13,
    kind: LineKinds.line,
    text: 'A única coisa que posso fazer é parar.###### Admirar esse céu.### E fingir que, no meio de todas aquelas estrelas##########, existe um lugar para mim.',
    nextLineId: 14,
    talker: '?',
  },
  {
    id: 14,
    kind: LineKinds.title,
    text: 'Não########.',
    nextLineId: 15,
    talker: null,
  },
  {
    id: 15,
    kind: LineKinds.line,
    text: 'Tem razão.',
    nextLineId: 16,
    talker: '?',
    initialDelay: 2000,
  },
  {
    id: 16,
    kind: LineKinds.line,
    text: 'Isso é burrice',
    nextLineId: 17,
    talker: '?',
  },
  {
    id: 17,
    kind: LineKinds.line,
    text: 'Ou ser muito ingênuo.',
    nextLineId: 18,
    talker: '?',
  },
  {
    id: 18,
    kind: LineKinds.title,
    text: 'Finalmente, você est%',
    nextLineId: 19,
  },
  {
    id: 19,
    kind: LineKinds.line,
    text: 'Espera#####, o que é aquilo?',
    nextLineId: 20,
    talker: '?',
  },
  {
    id: 20,
    kind: LineKinds.line,
    text: 'É tão####### lindo.',
    nextLineId: 21,
    talker: '?',
  },
  {
    id: 21,
    kind: LineKinds.title,
    text: 'Não me igno%',
    nextLineId: 22,
  },
  {
    id: 22,
    kind: LineKinds.line,
    text: 'Quieto, não estrague essa vista incrível.',
    nextLineId: 23,
    talker: '?',
  },
  {
    id: 23,
    kind: LineKinds.line,
    text: 'Nunca havia visto algo tão deslumbrante.',
    nextLineId: 24,
    talker: '?',
    firstOption: 'Chamar',
    secondOption: 'Olhar de mais perto',
    firstOptionLineId: 25,
    secondOptionLineId: 27,
  },
  {
    id: 25,
    kind: LineKinds.line,
    text: 'Ol-%',
    nextLineId: 26,
    talker: '?',
    initialDelay: 2000,
  },
  {
    id: 26,
    kind: LineKinds.line,
    text: 'Espera, o que eu tô fazendo? #######@Não deveria acordá-la.######### Além disso, não sei seu nome para que pudesse chamá-la.',
    nextLineId: 27,
    talker: '?',
  },
  {
    id: 27,
    kind: LineKinds.line,
    text: 'Talvez eu possa admirá-la de mais perto.',
    nextLineId: 28,
    talker: '?',
  },
  {
    id: 28,
    kind: LineKinds.line,
    text: 'Ela deve ficar mais próxima do outro lado da montanha. ######Certo.',
    nextLineId: 29,
    talker: '?',
  },
  {
    id: 29,
    kind: LineKinds.narrative,
    text: 'Ainda não sei o que me motivou a fazer isso. ##########Mas senti que valia a pena',
    nextLineId: 30,
  },
  {
    id: 30,
    kind: LineKinds.narrative,
    text: '"Por que aquele corpo celeste tanto me encantou? Será que todo mundo tinha visto o que eu acabara de ver?"',
    nextLineId: 31,
    initialDelay: 3000,
  },
  {
    id: 31,
    kind: LineKinds.narrative,
    text: 'Perguntas intermináveis ecoavam em meu interior e faziam-me ficar ainda mais intrigado com aquilo. #######E ainda mais aficionado por ela.',
    nextLineId: 32,
  },
  {
    id: 32,
    kind: LineKinds.narrative,
    text: 'Durante todo o trajeto, Ele não disse mais nada.######## A caminhada não durou tanto, mas eu nunca tinha visto Ele tão########### quieto.',
    nextLineId: 33,
  },
  {
    id: 33,
    kind: LineKinds.narrative,
    text: 'Enfim, . . .',
    nextLineId: 34,
  },
  {
    id: 34,
    kind: LineKinds.line,
    text: '...chegamos',
    nextLineId: 35,
    talker: '?',
  },
]