import { LineKinds, IStoryLine } from "@/interfaces/story_line";

export const lines: IStoryLine[] = [ 
  {
    id: 1,
    kind: LineKinds.title,
    text: 'O universo não me acolheu.',
    nextLineId: 2,
    talker: null,
  },
  {
    id: 2,
    kind: LineKinds.title,
    text: 'Mas não era dele que eu precisava.',
    nextLineId: 3,
    talker: null,
  },
  {
    id: 3,
    kind: LineKinds.title,
    text: 'Eu nunca precisei.',
    nextLineId: 4,
    talker: null,
  },
  {
    id: 4,
    kind: LineKinds.line,
    text: 'Na verdade, não é como se essa fosse a obrigação dele.',
    nextLineId: 5,
    talker: '?',
  },
  {
    id: 5,
    kind: LineKinds.line,
    text: 'Mas mesmo assim. ####Eu te entendo.########## Também gostaria de, ao menos uma vez, fazer parte de alguma coisa.',
    nextLineId: 6,
    talker: '?',
  },
  {
    id: 6,
    kind: LineKinds.line,
    text: 'Não necessariamente algo#### grande.',
    nextLineId: 7,
    talker: '?',
  },
  {
    id: 7,
    kind: LineKinds.line,
    text: 'Só algo que,######## sei lá, o qual eu pudesse chamar de##.###.###.## casa########?',
    nextLineId: 8,
    talker: '?',
  },
  {
    id: 8,
    kind: LineKinds.title,
    text: 'C#########A#########S#########A',
    nextLineId: 9,
  },
  {
    id: 9,
    kind: LineKinds.title,
    text: 'Casa se foi###########@há muito tempo.',
    nextLineId: 10,
    talker: null,
  },
  {
    id: 10,
    kind: LineKinds.line,
    text: 'Tem razão########, estou completamente sozinho.###### . ######.',
    nextLineId: 11,
    talker: '?',
  },
  {
    id: 11,
    kind: LineKinds.line,
    text: 'Eu poderia só#####.#####.#####.###### deixar tudo isso para trás.',
    nextLineId: 12,
    talker: '?',
  },
  {
    id: 12,
    kind: LineKinds.line,
    text: 'Não há nada para mim aqui.',
    nextLineId: 13,
    talker: '?',
  },
  {
    id: 13,
    kind: LineKinds.line,
    text: 'A única coisa que posso fazer é parar.###### Admirar esse céu.### E fingir que, no meio de todas aquelas estrelas##########, existe um lugar para mim.',
    nextLineId: 14,
    talker: '?',
  },
  {
    id: 14,
    kind: LineKinds.title,
    text: 'Não########.',
    nextLineId: 15,
    talker: null,
  },
  {
    id: 15,
    kind: LineKinds.line,
    text: 'Tem razão.',
    nextLineId: 16,
    talker: '?',
    initialDelay: 2000,
  },
  {
    id: 16,
    kind: LineKinds.line,
    text: 'Isso é burrice',
    nextLineId: 17,
    talker: '?',
  },
  {
    id: 17,
    kind: LineKinds.line,
    text: 'Ou ser muito ingênuo.',
    nextLineId: 18,
    talker: '?',
  },
]